### PR TITLE
Update callback according to SDK 6.9.1 interface.

### PR DESCRIPTION
**Pull request by felixzhang0703**

### CODE REVIEW

**Review by shiv-vungle — APPROVED** [review]
LGTM

**Comment by stanley-vungle** [comment]
@felixzhang0703 Can you also update the Readme.md with the information for the callbacks?

**Comment by felixzhang0703** [comment]
@stanley-vungle , updated README.md. Thanks for your comments!

**Review by stanley-vungle — APPROVED** [review]
LGTM

**Pull request merged**
